spring:
  datasource:
    url: jdbc:mysql://localhost:3306/overnight_db
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/migration.xml
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mail:
    host: smtp.gmail.com
    username: 2021JavaForTest@gmail.com
    password: plrsicvzxrkumdkj
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

overnight:
  images:
    folder: C:\Users\Toshiba\IdeaProjects\Overnight\images

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
  file:
    name: C:\Users\Toshiba\IdeaProjects\Overnight\log\application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}  %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}  %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.example: info